#Location of top -level MicroPython directory
MPY_DIR = C:/workspace/micropython
# Name of module
MOD = butterworth_cascaded_biquad
#Source files
SRC = butterworth_cascaded_biquad.c
# Architecture to build
ARCH = armv7m

# Compiler flags for Cortex-M33 with FPU
CFLAGS = -Wall -Wno-error
#Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk